accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
]

orders/urls.py
from django.urls import path

from .views import (MenuView, add_to_cart, cart, decrease_quantity,
                    increase_quantity, index, item_details, remove_from_cart)

app_name = "orders"

urlpatterns = [
    path("", index, name="home"),
    path("menu", MenuView.as_view(), name="menu"),
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    path("remove-from-cart/<ajdi>", remove_from_cart, name="remove-from-cart"),
    path("cart", cart, name="cart"),
    path("details/<slug>", item_details, name="item_details"),
    path("decrease/<ajdi>", decrease_quantity, name="decrease-quantity"),
    path("increase/<ajdi>", increase_quantity, name="increase-quantity"),
]

urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("orders.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

accounts/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.conf.global_settings import AUTH_USER_MODEL
from django.db import models
from django.db.models import ManyToManyField
from django.urls import reverse


class UserCart(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = ManyToManyField("CartItem")
    placed_date = models.DateTimeField(auto_now_add=True)
    value = models.DecimalField(default=0, max_digits=5, decimal_places=2)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user)

    def calculate_value(self):
        # Narazie zeruje potem dorobie
        self.value = 0
        for item in self.items.all():
            if item.size == "Small":
                self.value += item.item.small_price * item.quantity
            else:
                self.value += item.item.large_price * item.quantity
            for topping in item.topping.all():
                self.value += topping.price
        self.save()


class CartItem(models.Model):
    item = models.ForeignKey("Item", on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    size = models.CharField(
        max_length=8, choices=[("S", "Small"), ("L", "Large")], default="Small"
    )
    topping = models.ManyToManyField("Topping")

    # TODO: Get to know is it safe to pass such params this way
    def get_remove_from_cart_url(self):
        return reverse("orders:remove-from-cart", kwargs={"ajdi": self.id})

    def get_decrease_quantity_url(self):
        return reverse("orders:decrease-quantity", kwargs={"ajdi": self.id})

    def get_increase_quantity_url(self):
        return reverse("orders:increase-quantity", kwargs={"ajdi": self.id})

    def __str__(self):
        return f"{self.item.name}  sztuk: {self.quantity}  wielkosci: {self.size} dodatek: {self.topping.first()}"


class Item(models.Model):
    name = models.CharField(max_length=20)
    small_price = models.FloatField()
    large_price = models.FloatField(null=True, blank=True)
    slug = models.SlugField(max_length=6)
    category = models.ForeignKey("Category", on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Topping(models.Model):
    name = models.CharField(max_length=20)
    price = models.FloatField(default="2.00")

    def __str__(self):
        return self.name


class Deliverymen(models.Model):
    first_name = models.CharField(max_length=20)
    second_name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=10)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.first_name + " " + self.second_name

orders/forms.py
from django import forms

from .models import CartItem


# trzeba ustawić ifa dla kategorii i jak
# ma tylko small price to zeby nie bylo wyboru wielkosci
class ItemDetailsForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = ["size", "quantity", "topping"]

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

orders/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView

from .forms import ItemDetailsForm
from .models import *


def index(request):
    return render(request, "orders/index.html")


class MenuView(ListView):
    model = Item
    template_name = "orders/menu.html"


def cart(request):
    context = {"order": UserCart.objects.filter(user=request.user, completed=False)}
    return render(request, "orders/cart.html", context)


def item_details(request, slug):
    item = get_object_or_404(Item, slug=slug)
    form = ItemDetailsForm(request.POST or None)
    if form.is_valid():
        form.cleaned_data.update({"item": item})
        return add_to_cart(request=request, cart_item_data=form.cleaned_data)

    return render(request, "orders/itemDetails.html", {"form": form, "item": item})


def add_to_cart(request, cart_item_data):
    item_to_add = __create_cart_item(cart_item_data)
    user_cart, was_created = UserCart.objects.get_or_create(
        user=request.user, completed=False,
    )
    if was_created:
        user_cart.items.add(item_to_add)
    else:
        cart_item = user_cart.items.filter(
            item__name=item_to_add.item.name,
            size=item_to_add.size,
            topping=item_to_add.topping.first(),
        ).first()
        if cart_item:
            cart_item.quantity = item_to_add.quantity
        else:
            user_cart.items.add(item_to_add)
    user_cart.calculate_value()
    return redirect("orders:cart")


def __create_cart_item(cart_item_data: dict) -> CartItem:
    # Będzie działać dla jednego dodatku
    topping = cart_item_data.pop("topping")[0]
    cart_item = CartItem.objects.filter(
        item=cart_item_data["item"], size=cart_item_data["size"], topping=topping
    ).first()

    if not cart_item:
        cart_item = CartItem.objects.create(**cart_item_data)
        cart_item.topping.add(topping)
    else:
        cart_item.quantity += cart_item_data["quantity"]
    cart_item.save()
    return cart_item


def remove_from_cart(request, ajdi):
    order_qs = UserCart.objects.filter(user=request.user)
    if order_qs.exists():
        order = UserCart.objects.filter(user=request.user, completed=False)[0]
        items = order.items.filter(id=ajdi)
        if items.exists():
            order.items.remove(items.first())
    return redirect("orders:cart")


def decrease_quantity(request, ajdi):
    item = get_item(request.user, ajdi)
    if item:
        item.quantity -= 1
        item.save()
    return redirect("orders:cart")


def increase_quantity(request, ajdi):
    item = get_item(request.user, ajdi)
    if item:
        item.quantity += 1
        item.save()
    return redirect("orders:cart")

templates/base.html
{% load static %}
<html lang="en">
  <head>
   <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link href="{% static "orders/styles.css" %}" rel="stylesheet" type="text/css"/>

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

  <header>
      <div class="container">

          <img src="{% static "orders/images/pinokionavbar.jpg" %}" alt="logo" class="logo"/>

          <nav>
            <a href="/">Home</a>
            <a href="/menu">Menu</a>
            <a href="#">Contact</a>
          <div class="logging-in">
            {% if user.is_authenticated %}
                <a href="{% url 'orders:cart' %}"> {{ user.username }}</a>
                <a href="{% url 'logout' %}">logout</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
                <a href="{% url 'signup' %}">Sign up</a>
            {% endif %}
          </div>
          </nav>

      </div>
  </header>
         {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
          {% endif %}
      {% block body %}{% endblock %}
  </body>
</html>

templates/orders/base.html
{% load static %}
<html>
  <head>
  <link href="{% static "orders/styles.css" %}" rel="stylesheet" type="text/css"/>
      <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

  <header>
      <div class="container">

          <img src="{% static "orders/images/pinokionavbar.jpg" %}" alt="logo" class="logo"/>

          <nav>
              <ul>
                  <li><a href="#">Home</a></li>
                  <li><a href="#">Menu</a></li>
                  <li><a href="#">Directions</a></li>
                  <li><a href="#">Hours</a></li>
                  <li><a href="#">Sicilian vs. Regular</a></li>
                  <li><a href="#">Contact us</a></li>
                  {% if user.is_authenticated %}
                      <li>{{ user.username }}</li>
                      <li><a href="{% url 'logout' %}">logout</a></li>
                    {% else %}
                      <li class="login-button"><a href="{% url 'login' %}">Login</a></li>
{#                      <li><a href="{% url 'register' %}">Register</a></li>#}
                  {% endif %}
              </ul>
          </nav>
      </div>
  </header>

      {% block body %}{% endblock %}
  </body>
</html>

templates/orders/cart.html
{% extends "base.html" %}
{% block title %}
    Pizzernia
{% endblock %}
{% block body %}
    {% for order in order.all %}
        <h1>{{ order.user }}'s cart</h1>
        <p>Wartość zamówienia: {{ order.value }}</p>
        {% if order.items.all %}
            {% for item in order.items.all %}
            <p class="name"> {{ item }} </p>
{#            </p><a href="{{ item.item.get_remove_from_cart_url }}">remove from cart</a>#}
{#                <a href="{{ item.item.get_decrease_quantity_url }}">  minus</a>#}
{#                <a href="{{ item.item.get_add_to_cart_url }}">  plus</a>#}
                <br>
            {% endfor %}
        {% else %}
            <h3>is empty</h3>
        {% endif %}
    {% endfor %}
{% endblock %}

templates/orders/index.html
{% extends "base.html" %}
{% block title %}
    Pizzernia
{% endblock %}
{% block body %}
    <h1>Siemanko witam w mojej pizzerni</h1>
{% endblock %}

templates/orders/itemDetails.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Item details</title>
</head>

<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add to cart">
    </form>
</body>
</html>

templates/orders/menu.html
{% extends "base.html" %}
{% block title %}
    Pizzernia-menu
{% endblock %}
{% block body %}
    {% load static %}
    <script src="{% static 'orders/cart.js' %}"></script>
    <h1>Menu</h1>
    <table>
        <tr>
            {% for item in object_list %}
                <th><a href="#">{{ item.get_category_display }}</a></th>
            {% endfor %}
        </tr>
        <tr>
            <th>Name</th>
            <th>Small</th>
            <th>Large</th>
        </tr>


                {% for item in object_list %}
{#                    raw html form with hidden value#}
                    <form action="{% url 'orders:item_details' item.slug %}" method="post">
                    {% csrf_token %}
                    <tr>
                        <th>{{ item }}</th>
                        <th>{{ item.small_price }}</th>
                        <th>{{ item.large_price }}</th>
                        <input type="hidden" value="{{ item.slug }}">
                        <th><input type="submit" value="Order"></th>
                    </tr>
            </form>
        {% endfor %}
    </table>
{% endblock %}